// GENERATED by levels-src/transcribe-picture-icons.ts - do not edit by hand.
//
// One entry per picture key the committed art manifest carries: how many icons that picture
// has, which is `Bilddatei::anzBildchen()` = `(breite/gric) * (hoehe/gric)` at `gric` =
// 32 (`src/bilddatei.cpp:205`), transcribed from upstream's spritesheets.
//
// It is committed rather than computed at build time because upstream's spritesheets are
// GPL-2.0 and deliberately not shipped - see scripts/check-no-upstream-art.sh - so at run
// time there is no image to measure. The artwork is this project's own, so the count is a
// fact about it, and the honest starting value is the number of icons the Cual that draws it
// expects.
//
// Two things depend on it, and both fail visibly when it is wrong:
//
//   - `Sorte::ladeCualEvents` (`src/sorte.cpp:104-130`) picks `default3` for more than one
//     picture file, `default2`/`default2g` for one file with several icons and `default1`
//     for a single-icon file. Those draw visibly different things.
//   - `BildStapel::speichereBild` refuses a `pos` outside the count, because blitting past
//     the end of a file would draw whatever follows it.
//
// Measured from 912 images on disk, covering 222 of 226 manifest
// keys. The figure after each key is the file it came from and that file's pixel size, so a
// transcription slip is checkable against the image rather than taken on trust.

/** How many icons each picture key has. Zero means the key is not a picture. */
export const PICTURE_ICONS: ReadonlyMap<string, number> = new Map<string, number>([
  ["aBoxFractal.xpm", 9], // aBoxFractal.xpm.gz 96x96
  ["aCantorSet.xpm", 18], // aCantorSet.xpm.gz 96x192
  ["aDragon.xpm", 8], // aDragon.xpm.gz 128x64
  ["baAliens.xpm", 8], // baAliens.xpm.gz 128x64
  ["baBlue.xpm", 2], // baBlue.xpm.gz 64x32
  ["baGreen.xpm", 2], // baGreen.xpm.gz 64x32
  ["baRed.xpm", 2], // baRed.xpm.gz 64x32
  ["baYellow.xpm", 2], // baYellow.xpm.gz 64x32
  ["bbBonus.xpm", 12], // bbBonus.xpm.gz 128x96
  ["bcEmpty1.xpm", 200], // bcEmpty1.xpm.gz 320x640
  ["bddisco.xpm", 12], // bddisco.xpm.gz 128x96
  ["blBuchstabe.xpm", 27], // blBuchstabe.xpm.gz 288x96
  ["blFragezeichen.xpm", 1], // blFragezeichen.xpm.gz 32x32
  ["bmKarten.xpm", 30], // bmKarten.xpm.gz 480x64
  ["bmTisch.xpm", 1], // bmTisch.xpm.gz 32x32
  ["bpEis.xpm", 8], // bpEis.xpm.gz 128x64
  ["bpFreezePingu.xpm", 5], // bpFreezePingu.xpm.gz 160x32
  ["bpIglu.xpm", 16], // bpIglu.xpm.gz 128x128
  ["bpPingu.xpm", 16], // bpPingu.xpm.gz 128x128
  ["bpSchnee.xpm", 4], // bpSchnee.xpm.gz 128x32
  ["bpStein.xpm", 1], // bpStein.xpm.gz 32x32
  ["btGrey.xpm", 16], // btGrey.xpm.gz 128x128
  ["btScore.xpm", 20], // btScore.xpm.gz 160x128
  ["btTetris.xpm", 7], // btTetris.xpm.gz 224x32
  ["bxBaer32.xpm", 1], // bxBaer32.xpm.gz 32x32
  ["dnBlack.xpm", 16], // dnBlack.xpm.gz 128x128
  ["dnBlack2.xpm", 16], // dnBlack2.xpm.gz 128x128
  ["dnBlue.xpm", 16], // dnBlue.xpm.gz 128x128
  ["dnGray.xpm", 16], // dnGray.xpm.gz 128x128
  ["dnGreen1.xpm", 16], // dnGreen1.xpm.gz 128x128
  ["dnRed1.xpm", 16], // dnRed1.xpm.gz 128x128
  ["elBlack.xpm", 16], // elBlack.xpm.gz 128x128
  ["elBlue.xpm", 16], // elBlue.xpm.gz 128x128
  ["elGray.xpm", 1], // elGray.xpm.gz 32x32
  ["elGreen.xpm", 16], // elGreen.xpm.gz 128x128
  ["elRed.xpm", 16], // elRed.xpm.gz 128x128
  ["elYellow.xpm", 16], // elYellow.xpm.gz 128x128
  ["i3Dreieck.xpm", 27], // i3Dreieck.xpm.gz 288x96
  ["i3Gitter.xpm", 27], // i3Gitter.xpm.gz 288x96
  ["i3Grau.xpm", 10], // i3Grau.xpm.gz 160x64
  ["i3Kreis.xpm", 27], // i3Kreis.xpm.gz 288x96
  ["i3Plus.xpm", 27], // i3Plus.xpm.gz 288x96
  ["i3Quadrat.xpm", 27], // i3Quadrat.xpm.gz 288x96
  ["i3Stern.xpm", 27], // i3Stern.xpm.gz 288x96
  ["i6Blau.xpm", 8], // i6Blau.xpm.gz 128x64
  ["i6Gelb.xpm", 8], // i6Gelb.xpm.gz 128x64
  ["i6Grau.xpm", 1], // i6Grau.xpm.gz 32x32
  ["i6Hintergrund.xpm", 2], // i6Hintergrund.xpm.gz 64x32
  ["i6Lila.xpm", 8], // i6Lila.xpm.gz 128x64
  ["i6Rot.xpm", 8], // i6Rot.xpm.gz 128x64
  ["i6Weiss.xpm", 8], // i6Weiss.xpm.gz 128x64
  ["iaAusdruck.xpm", 9], // iaAusdruck.xpm.gz 96x96
  ["iaBefehl.xpm", 9], // iaBefehl.xpm.gz 96x96
  ["iaError.xpm", 10], // iaError.xpm.gz 160x64
  ["iaGrau.xpm", 1], // iaGrau.xpm.gz 32x32
  ["iaString.xpm", 9], // iaString.xpm.gz 96x96
  ["iaZahl.xpm", 9], // iaZahl.xpm.gz 96x96
  ["ibBaelle.xpm", 16], // ibBaelle.xpm.gz 128x128
  ["ibGrauball.xpm", 1], // ibGrauball.xpm.gz 32x32
  ["ibKegelPink.xpm", 4], // ibKegelPink.xpm.gz 32x128
  ["ibkBunt.xpm", 20], // ibkBunt.xpm.gz 128x160
  ["ibkRahmen.xpm", 3], // ibkRahmen.xpm.gz 96x32
  ["ibwBlaeschen.xpm", 8], // ibwBlaeschen.xpm.gz 128x64
  ["ibwSchuh.xpm", 1], // ibwSchuh.xpm.gz 32x32
  ["ieGelb.xpm", 20], // ieGelb.xpm.gz 128x160
  ["ieGras.xpm", 12], // ieGras.xpm.gz 128x96
  ["ieGrau.xpm", 12], // ieGrau.xpm.gz 128x96
  ["ieGruen.xpm", 20], // ieGruen.xpm.gz 128x160
  ["ieRosa.xpm", 20], // ieRosa.xpm.gz 128x160
  ["ieRot.xpm", 20], // ieRot.xpm.gz 128x160
  ["igGo.xpm", 1], // igGo.xpm.gz 32x32
  ["igSchwarz.xpm", 3], // igSchwarz.xpm.gz 96x32
  ["ihBlau.xpm", 2], // ihBlau.xpm.gz 64x32
  ["ihBunt.xpm", 1], // ihBunt.xpm.gz 32x32
  ["ihGrau.xpm", 1], // ihGrau.xpm.gz 32x32
  ["ihGruen.xpm", 2], // ihGruen.xpm.gz 64x32
  ["ihLila.xpm", 2], // ihLila.xpm.gz 64x32
  ["ihRot.xpm", 2], // ihRot.xpm.gz 64x32
  ["ilBlase.xpm", 21], // ilBlase.xpm.gz 96x224
  ["ilDing.xpm", 6], // ilDing.xpm.gz 96x64
  ["ilTuer.xpm", 40], // ilTuer.xpm.gz 256x160
  ["ilVogelL.xpm", 12], // ilVogelL.xpm.gz 128x96
  ["inGelb.xpm", 16], // inGelb.xpm.gz 128x128
  ["inGras.xpm", 12], // inGras.xpm.gz 192x64
  ["inGrau.xpm", 8], // inGrau.xpm.gz 128x64
  ["inGruen.xpm", 16], // inGruen.xpm.gz 128x128
  ["inOrangeNasen.xpm", 16], // inOrangeNasen.xpm.gz 128x128
  ["inRosaNasen.xpm", 16], // inRosaNasen.xpm.gz 128x128
  ["inSchwarz.xpm", 16], // inSchwarz.xpm.gz 128x128
  ["ipGrau.xpm", 1], // ipGrau.xpm.gz 32x32
  ["ipHoch.xpm", 6], // ipHoch.xpm.gz 64x96
  ["ipHochRunter.xpm", 6], // ipHochRunter.xpm.gz 64x96
  ["ipLinks.xpm", 6], // ipLinks.xpm.gz 64x96
  ["ipLinksRechts.xpm", 6], // ipLinksRechts.xpm.gz 64x96
  ["ipRechts.xpm", 6], // ipRechts.xpm.gz 64x96
  ["ipRunter.xpm", 6], // ipRunter.xpm.gz 64x96
  ["ipStart.xpm", 24], // ipStart.xpm.gz 192x128
  ["isVerbindung.xpm", 4], // isVerbindung.xpm.gz 64x64
  ["ispRest.xpm", 2], // ispRest.xpm.gz 64x32
  ["ispSchwarz.xpm", 5], // ispSchwarz.xpm.gz 160x32
  ["itBlau.xpm", 30], // itBlau.xpm.gz 160x192
  ["itGras.xpm", 30], // itGras.xpm.gz 160x192
  ["itGrau.xpm", 30], // itGrau.xpm.gz 160x192
  ["ithSitz.xpm", 9], // ithSitz.xpm.gz 96x96
  ["itrBraun.xpm", 27], // itrBraun.xpm.gz 96x288
  ["ivFeuer1.xpm", 16], // ivFeuer1.xpm.gz 128x128
  ["iwBaum.xpm", 16], // iwBaum.xpm.gz 128x128
  ["iwErde.xpm", 5], // iwErde.xpm.gz 160x32
  ["iwKreis.xpm", 4], // iwKreis.xpm.gz 64x64
  ["iwQuadrat.xpm", 4], // iwQuadrat.xpm.gz 64x64
  ["iwRaute.xpm", 4], // iwRaute.xpm.gz 64x64
  ["iwaBad.xpm", 12], // iwaBad.xpm.gz 96x128
  ["iwaBeton.xpm", 12], // iwaBeton.xpm.gz 96x128
  ["iwaParkett.xpm", 12], // iwaParkett.xpm.gz 96x128
  ["iwaTeppich.xpm", 12], // iwaTeppich.xpm.gz 96x128
  ["jhBallons.xpm", 16], // jhBallons.xpm.gz 128x128
  ["jhBlitz.xpm", 16], // jhBlitz.xpm.gz 128x128
  ["jhDrachensteigen.xpm", 16], // jhDrachensteigen.xpm.gz 128x128
  ["jhGraueWolke.xpm", 1], // jhGraueWolke.xpm.gz 32x32
  ["jhHelleWolken.xpm", 16], // jhHelleWolken.xpm.gz 128x128
  ["jhSonne.xpm", 15], // jhSonne.xpm.gz 160x96
  ["jhVoegel.xpm", 16], // jhVoegel.xpm.gz 128x128
  ["jjExtra.xpm", 16], // jjExtra.xpm.gz 128x128
  ["jsGelbFlach.xpm", 16], // jsGelbFlach.xpm.gz 128x128
  ["jsGrauLoch.xpm", 16], // jsGrauLoch.xpm.gz 128x128
  ["jsGruenGras.xpm", 6], // jsGruenGras.xpm.gz 96x64
  ["jsOrangeKetten_5.xpm", 6], // jsOrangeKetten_5.xpm.gz 96x64
  ["jsOrangeKreuz_2.xpm", 2], // jsOrangeKreuz_2.xpm.gz 64x32
  ["jsRotHexen_2.xpm", 4], // jsRotHexen_2.xpm.gz 64x64
  ["kmBier.xpm", 1], // kmBier.xpm.gz 32x32
  ["kmMuell.xpm", 1], // kmMuell.xpm.gz 32x32
  ["kmPizza.xpm", 6], // kmPizza.xpm.gz 96x64
  ["kmSofa.xpm", 12], // kmSofa.xpm.gz 128x96
  ["kmTasse.xpm", 16], // kmTasse.xpm.gz 128x128
  ["lbBlack.xpm", 1], // lbBlack.xpm 32x32
  ["lbBomb.xpm", 5], // lbBomb.xpm 160x32
  ["lbGray.xpm", 1], // lbGray.xpm 32x32
  ["lpGreen.xpm", 72], // lpGreen.xpm.gz 256x288
  ["lpRed.xpm", 72], // lpRed.xpm.gz 256x288
  ["lpStart.xpm", 4], // lpStart.xpm.gz 128x32
  ["lpWhite.xpm", 72], // lpWhite.xpm.gz 256x288
  ["lpYellow.xpm", 72], // lpYellow.xpm.gz 256x288
  ["lrEis.xpm", 5], // lrEis.xpm.gz 160x32
  ["lrKamin.xpm", 52], // lrKamin.xpm.gz 128x416
  ["lrOfen.xpm", 4], // lrOfen.xpm.gz 128x32
  ["lrWasser.xpm", 28], // lrWasser.xpm.gz 128x224
  ["lreAlle.xpm", 18], // lreAlle.xpm.gz 96x192
  ["ltCannon.xpm", 10], // ltCannon.xpm 64x160
  ["ltGray.xpm", 1], // ltGray.xpm 32x32
  ["ltParatrooper.xpm", 9], // ltParatrooper.xpm 288x32
  ["lwBroken.xpm", 1], // lwBroken.xpm.gz 32x32
  ["lwGray.xpm", 1], // lwGray.xpm.gz 32x32
  ["lwGreen.xpm", 16], // lwGreen.xpm.gz 128x128
  ["lwRed.xpm", 16], // lwRed.xpm.gz 128x128
  ["lwRolladen.xpm", 16], // lwRolladen.xpm.gz 128x128
  ["m6Dick.xpm", 8], // m6Dick.xpm.gz 128x64
  ["m6Gras.xpm", 12], // m6Gras.xpm.gz 32x384
  ["m6Grau.xpm", 1], // m6Grau.xpm.gz 32x32
  ["maLidA.xpm", 8], // maLidA.xpm.gz 128x64
  ["maeSchema.xpm", 4], // maeSchema.xpm.gz 64x64
  ["manGras.xpm", 4], // manGras.xpm.gz 64x64
  ["manGrau.xpm", 4], // manGrau.xpm.gz 64x64
  ["manKoepfe1.xpm", 16], // manKoepfe1.xpm.gz 64x256
  ["mbBunt.xpm", 136], // mbBunt.xpm.gz 544x256
  ["mbSchmelz1.xpm", 512], // mbSchmelz1.xpm.gz 512x1024
  ["mbUnbunt.xpm", 17], // mbUnbunt.xpm.gz 544x32
  ["mbaBand1.xpm", 3], // mbaBand1.xpm 96x32
  ["mbaGras.xpm", 3], // mbaGras.xpm 96x32
  ["mbaGrau.xpm", 3], // mbaGrau.xpm 96x32
  ["mbmSchnell.xpm", 10], // mbmSchnell.xpm.gz 64x160
  ["mdBoden.xpm", 1], // mdBoden.xpm.gz 32x32
  ["mdPlastik.xpm", 6], // mdPlastik.xpm.gz 64x96
  ["mfaCabbage.xpm", 6], // mfaCabbage.xpm 96x64
  ["mfaFence.xpm", 15], // mfaFence.xpm 96x160
  ["mfaMaize.xpm", 6], // mfaMaize.xpm 96x64
  ["mfaRoad.xpm", 16], // mfaRoad.xpm 128x128
  ["mfaWater.xpm", 6], // mfaWater.xpm 96x64
  ["mfaWheat.xpm", 6], // mfaWheat.xpm 96x64
  ["mffisch1.xpm", 28], // mffisch1.xpm.gz 128x224
  ["mflAlles.xpm", 192], // mflAlles.xpm.gz 512x384
  ["mfmuschel.xpm", 7], // mfmuschel.xpm.gz 224x32
  ["mfqualle.xpm", 3], // mfqualle.xpm.gz 96x32
  ["mgsGoldVerbind.xpm", 4], // mgsGoldVerbind.xpm 64x64
  ["mgsSilber.xpm", 2], // mgsSilber.xpm 64x32
  ["mgsWeiss.xpm", 1], // mgsWeiss.xpm 32x32
  ["mihGarten.xpm", 9], // mihGarten.xpm 96x96
  ["mihLoch.xpm", 1], // mihLoch.xpm 32x32
  ["mihStein.xpm", 1], // mihStein.xpm 32x32
  ["mjZeug1.xpm", 15], // mjZeug1.xpm.gz 96x160
  ["mkKolben.xpm", 16], // mkKolben.xpm.gz 128x128
  ["mkaFuenfeckKacheln.xpm", 84], // mkaFuenfeckKacheln.xpm.gz 192x448
  ["mkaRhombusLeer.xpm", 6], // mkaRhombusLeer.xpm.gz 64x96
  ["mkaSechseckKacheln.xpm", 42], // mkaSechseckKacheln.xpm.gz 192x224
  ["mkaViereckKacheln.xpm", 70], // mkaViereckKacheln.xpm.gz 160x448
  ["mlGras.xpm", 16], // mlGras.xpm.gz 128x128
  ["mlGrau.xpm", 16], // mlGrau.xpm.gz 128x128
  ["mlSorte2.xpm", 16], // mlSorte2.xpm.gz 128x128
  ["mmBlau.xpm", 8], // mmBlau.xpm 64x128
  ["mmGrasgrau.xpm", 2], // mmGrasgrau.xpm 64x32
  ["mnv1.xpm", 4], // mnv1.xpm.gz 64x64
  ["moAnemone.xpm", 4], // moAnemone.xpm.gz 128x32
  ["moFisch.xpm", 1], // moFisch.xpm.gz 32x32
  ["moOctopus1.xpm", 9], // moOctopus1.xpm.gz 96x96
  ["mpAlle.xpm", 180], // mpAlle.xpm.gz 160x1152
  ["mreGrasgrau.xpm", 2], // mreGrasgrau.xpm 64x32
  ["mreZahl1.xpm", 26], // mreZahl1.xpm.gz 64x416
  ["mrpAlle.xpm", 8], // mrpAlle.xpm.gz 64x128
  ["msGreen.xpm", 5], // msGreen.xpm.gz 160x32
  ["msRed.xpm", 5], // msRed.xpm.gz 160x32
  ["mscLeer.xpm", 200], // mscLeer.xpm.gz 320x640
  ["mseGG.xpm", 256], // mseGG.xpm.gz 512x512
  ["mseKind.xpm", 256], // mseKind.xpm.gz 512x512
  ["mtRacket.xpm", 3], // mtRacket.xpm.gz 32x96
  ["mtWall.xpm", 1], // mtWall.xpm.gz 32x32
  ["mtr1.xpm", 6], // mtr1.xpm.gz 96x64
  ["mtrGras.xpm", 1], // mtrGras.xpm 32x32
  ["mtrGrau.xpm", 1], // mtrGrau.xpm 32x32
  ["mzZahn.xpm", 27], // mzZahn.xpm.gz 96x288
  ["mziAlle.xpm", 10], // mziAlle.xpm.gz 160x64
  ["sbSunglas.xpm", 3], // sbSunglas.xpm.gz 96x32
  ["spLabyrinth.xpm", 20], // spLabyrinth.xpm.gz 128x160
  ["spPfeil.xpm", 20], // spPfeil.xpm.gz 128x160
  ["Grau", 0],
  ["Starr", 0],
  ["Start", 0],
  ["start_dummy", 0],
]);

/** The icon count for a key, or null when the table does not carry it. */
export function iconCountOf(key: string): number | null {
  return PICTURE_ICONS.get(key) ?? null;
}
