#!/usr/bin/env bash
# Regenerate the committed list of upstream artwork digests.
#
# Copyright (C) 2026 Sebastian Ryszard Kruk (dev@kruk.me)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Writes scripts/upstream-art-digests.sha256 from a fetched upstream tree. Both
# spellings of every sprite: as shipped, and decompressed, so a sprite cannot get
# past the artwork check by being re-compressed on the way in.
#
# This needs the tree and is therefore not part of `make check` - CI has no upstream
# tree, which is the whole reason the digests are committed. Run it deliberately when
# the upstream version changes, and commit the result: the set is fixed per release,
# so a new release is a moment to re-verify rather than something to drift through.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

UPSTREAM="${CUYO_DATA_DIR:-.context/upstream-cuyo/data}/pics"
OUT="scripts/upstream-art-digests.sha256"

if [ ! -d "$UPSTREAM" ]; then
  echo "art-digests: no upstream artwork at $UPSTREAM" >&2
  echo "  Run 'make fetch-corpus' first." >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

count=0
while IFS= read -r sprite; do
  sha256sum "$sprite" | cut -d' ' -f1 >> "$tmp"
  case "$sprite" in
    *.gz) gzip -cd "$sprite" 2>/dev/null | sha256sum | cut -d' ' -f1 >> "$tmp" ;;
  esac
  count=$((count + 1))
done < <(find "$UPSTREAM" -maxdepth 1 -type f)

if [ "$count" -lt 900 ]; then
  echo "art-digests: only $count sprites at $UPSTREAM, expected 912" >&2
  echo "  A short list would make the artwork check check less than it appears to." >&2
  exit 1
fi

sort -u -o "$tmp" "$tmp"
digests="$(wc -l < "$tmp" | tr -d ' ')"

{
  printf '%s\n' \
    "# SHA-256 digests of upstream Cuyo's artwork, which this project does not ship." \
    "#" \
    "# Upstream's 912 spritesheets under \`data/pics/\` are GPL-2.0-or-later, and copying them" \
    "# would be legally permitted. They are not copied because this project draws its own, and" \
    "# a reimplementation that ships someone else's pixels is a repackaging." \
    "#" \
    "# This file is what makes that decision checkable *without* upstream's tree. The" \
    "# digests are of every sprite both as shipped and decompressed, so a sprite cannot get" \
    "# in by being renamed or re-compressed. $digests digests, about 110 kB." \
    "#" \
    "# Generated by \`make art-digests\`, which reads a fetched upstream tree. The set is" \
    "# fixed: the sprites come from the SHA-256-verified \`cuyo_2.1.0.orig.tar.gz\`, so a new" \
    "# upstream release means regenerating this deliberately rather than drifting quietly." \
    "#" \
    "# Do not edit by hand."
  cat "$tmp"
} > "$OUT"

echo "art-digests: $digests digests from $count sprites written to $OUT"
